// Autogenerated and enriched feature catalog for Happy Paws Viva Playbook

export interface UserStory {
  id: string;
  role: "adopter" | "foster" | "transporter" | "sponsor" | "veterinarian" | "administrator";
  userStory: string;
  functionality: string;
  description: string;
  platform: "Mobile (Flutter)" | "Web (Next.js)" | "Cross-platform";
  demoSteps: string[];
  vivaInsight?: string;
  endpoints?: string[];
  screenshots?: { caption: string; placeholder: string }[];
}

export interface RoleCategory {
  id: string;
  name: string;
  iconName: string;
  color: string;
  description: string;
  storiesCount: number;
}

export const ROLE_CATEGORIES: RoleCategory[] = [
  {
    "id": "adopter",
    "name": "Adopter and owner",
    "iconName": "User",
    "color": "teal",
    "description": "Browse pets, lifestyle matching quiz, submit adoptions, rescue reporting",
    "storiesCount": 19
  },
  {
    "id": "administrator",
    "name": "Administrator",
    "iconName": "ShieldCheck",
    "color": "blue",
    "description": "Live rescue map, KYC approvals, content moderation, user management",
    "storiesCount": 14
  },
  {
    "id": "foster",
    "name": "Foster",
    "iconName": "HeartHandshake",
    "color": "indigo",
    "description": "Temporary placements, case status updates, medical treatments, handovers",
    "storiesCount": 18
  },
  {
    "id": "transporter",
    "name": "Transporter",
    "iconName": "Truck",
    "color": "emerald",
    "description": "Animal movement tasks, transit tracking, route verification, handovers",
    "storiesCount": 12
  },
  {
    "id": "sponsor",
    "name": "Sponsor and donor",
    "iconName": "Coins",
    "color": "amber",
    "description": "Pledge financial and supply support, track case recovery progress",
    "storiesCount": 8
  },
  {
    "id": "veterinarian",
    "name": "Veterinarian",
    "iconName": "Stethoscope",
    "color": "rose",
    "description": "Clinical KYC, triage review, AI urgency verification, medical guidance",
    "storiesCount": 8
  }
];

export const USER_STORIES: UserStory[] = [
  {
    "id": "administrator-01",
    "role": "administrator",
    "userStory": "As an administrator, I want to log in to the web administration panel so I can access verification and case data.",
    "functionality": "Login and authentication",
    "description": "Signs in to the web administration panel with elevated, role-based access enforced through JWT.",
    "platform": "Cross-platform",
    "demoSteps": [
      "Navigate to Login and authentication on Cross-platform.",
      "Demonstrate log in to the web administration panel.",
      "Verify: Signs in to the web administration panel with elevated, role-based access enforced through JWT."
    ],
    "vivaInsight": "Explain how login and authentication operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/auth/admin/login",
      "POST /api/auth/admin/verify-otp",
      "GET /api/auth/admin/me"
    ],
    "screenshots": [
      {
        "caption": "Login and authentication view on Cross-platform",
        "placeholder": "/screenshots/administrator/administrator-01-main.png"
      }
    ]
  },
  {
    "id": "administrator-02",
    "role": "administrator",
    "userStory": "As an administrator, I want to review identity verification documents so I can approve or reject accounts before they gain full privileges.",
    "functionality": "Identity verification review",
    "description": "Inspects a submitted identity document, clinic registration, or license for any role and approves or rejects it before the account gains full privileges.",
    "platform": "Web (Next.js)",
    "demoSteps": [
      "Navigate to Identity verification review on Web (Next.js).",
      "Demonstrate review identity verification documents.",
      "Verify: Inspects a submitted identity document, clinic registration, or license for any role and approves or rejects it before the account gains full privileges."
    ],
    "vivaInsight": "Explain how identity verification review operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/admin/verifications",
      "PUT /api/admin/verifications/{id}/approve",
      "PUT /api/admin/verifications/{id}/reject"
    ],
    "screenshots": [
      {
        "caption": "Identity verification review view on Web (Next.js)",
        "placeholder": "/screenshots/administrator/administrator-02-main.png"
      }
    ]
  },
  {
    "id": "administrator-03",
    "role": "administrator",
    "userStory": "As an administrator, I want to view a live case map so I can coordinate several simultaneous rescues.",
    "functionality": "Live case map and rescue coordination",
    "description": "Views all active rescue cases plotted on a map, monitors their AI-assigned urgency and current status, and follows each one through to resolution.",
    "platform": "Web (Next.js)",
    "demoSteps": [
      "Navigate to Live case map and rescue coordination on Web (Next.js).",
      "Demonstrate view a live case map.",
      "Verify: Views all active rescue cases plotted on a map, monitors their AI-assigned urgency and current status, and follows each one through to resolution."
    ],
    "vivaInsight": "Explain how live case map and rescue coordination operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/admin/rescues",
      "GET /api/v1/admin/rescues/map"
    ],
    "screenshots": [
      {
        "caption": "Live case map and rescue coordination view on Web (Next.js)",
        "placeholder": "/screenshots/administrator/administrator-03-main.png"
      }
    ]
  },
  {
    "id": "administrator-04",
    "role": "administrator",
    "userStory": "As an administrator, I want to review AI triage and override Gemini's urgency classification when necessary so I can prevent wrong decisions.",
    "functionality": "AI triage oversight",
    "description": "Reviews and, where necessary, overrides Gemini’s urgency classification for a reported case, alongside the same override available to a veterinarian.",
    "platform": "Web (Next.js)",
    "demoSteps": [
      "Navigate to AI triage oversight on Web (Next.js).",
      "Demonstrate review AI triage and override Gemini's urgency classification when necessary.",
      "Verify: Reviews and, where necessary, overrides Gemini’s urgency classification for a reported case, alongside the same override available to a veterinarian."
    ],
    "vivaInsight": "Explain how ai triage oversight operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "PATCH /api/v1/admin/rescues/{postId}/urgency",
      "POST /api/v1/community/rescue-triage/assess"
    ],
    "screenshots": [
      {
        "caption": "AI triage oversight view on Web (Next.js)",
        "placeholder": "/screenshots/administrator/administrator-04-main.png"
      }
    ]
  },
  {
    "id": "administrator-05",
    "role": "administrator",
    "userStory": "As an administrator, I want to moderate content so I can remove listings or messages that violate platform rules or raise fraud concerns.",
    "functionality": "Content moderation",
    "description": "Reviews and removes adoption listings, messages, or profiles that violate platform rules or raise a fraud concern.",
    "platform": "Web (Next.js)",
    "demoSteps": [
      "Navigate to Content moderation on Web (Next.js).",
      "Demonstrate moderate content.",
      "Verify: Reviews and removes adoption listings, messages, or profiles that violate platform rules or raise a fraud concern."
    ],
    "vivaInsight": "Explain how content moderation operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/admin/posts",
      "PATCH /api/v1/admin/posts/{postId}/approve",
      "DELETE /api/v1/admin/posts/{postId}/permanent"
    ],
    "screenshots": [
      {
        "caption": "Content moderation view on Web (Next.js)",
        "placeholder": "/screenshots/administrator/administrator-05-main.png"
      }
    ]
  },
  {
    "id": "administrator-06",
    "role": "administrator",
    "userStory": "As an administrator, I want to manage user accounts so I can activate, suspend, or remove them if there is evidence of misuse.",
    "functionality": "User account management",
    "description": "Activates, suspends, or removes an account, including one already verified, if evidence of misuse appears.",
    "platform": "Web (Next.js)",
    "demoSteps": [
      "Navigate to User account management on Web (Next.js).",
      "Demonstrate manage user accounts.",
      "Verify: Activates, suspends, or removes an account, including one already verified, if evidence of misuse appears."
    ],
    "vivaInsight": "Explain how user account management operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/admin/users",
      "GET /api/admin/users/{id}",
      "PATCH /api/admin/users/{id}/status",
      "PUT /api/admin/users/{id}/roles"
    ],
    "screenshots": [
      {
        "caption": "User account management view on Web (Next.js)",
        "placeholder": "/screenshots/administrator/administrator-06-main.png"
      }
    ]
  },
  {
    "id": "administrator-07",
    "role": "administrator",
    "userStory": "As an administrator, I want to handle reputation and disputes so I can adjust points or badges manually when required.",
    "functionality": "Reputation and dispute handling",
    "description": "Adjusts reputation points or trust badges manually where a dispute between users requires it.",
    "platform": "Web (Next.js)",
    "demoSteps": [
      "Navigate to Reputation and dispute handling on Web (Next.js).",
      "Demonstrate handle reputation and disputes.",
      "Verify: Adjusts reputation points or trust badges manually where a dispute between users requires it."
    ],
    "vivaInsight": "Explain how reputation and dispute handling operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/admin/users/{id}/reputation"
    ],
    "screenshots": [
      {
        "caption": "Reputation and dispute handling view on Web (Next.js)",
        "placeholder": "/screenshots/administrator/administrator-07-main.png"
      }
    ]
  },
  {
    "id": "administrator-08",
    "role": "administrator",
    "userStory": "As an administrator, I want to view an admin dashboard so I can see a summary of pending verifications, open cases, and overall platform activity.",
    "functionality": "Admin dashboard and reporting",
    "description": "Sees a summary of pending verifications, open cases, and overall platform activity from a single web dashboard.",
    "platform": "Web (Next.js)",
    "demoSteps": [
      "Navigate to Admin dashboard and reporting on Web (Next.js).",
      "Demonstrate view an admin dashboard.",
      "Verify: Sees a summary of pending verifications, open cases, and overall platform activity from a single web dashboard."
    ],
    "vivaInsight": "Explain how admin dashboard and reporting operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/admin/analytics/user-growth",
      "GET /api/admin/analytics/roles-summary",
      "GET /api/admin/verifications"
    ],
    "screenshots": [
      {
        "caption": "Admin dashboard and reporting view on Web (Next.js)",
        "placeholder": "/screenshots/administrator/administrator-08-main.png"
      }
    ]
  },
  {
    "id": "administrator-09",
    "role": "administrator",
    "userStory": "As an administrator, I want to see all rescue cases with an approved applicant in the Rescues tab so I can monitor active fostering assignments.",
    "functionality": "Rescue case monitoring",
    "description": "Views all active rescues with an approved applicant in the rescues tab.",
    "platform": "Web (Next.js)",
    "demoSteps": [
      "Navigate to Rescue case monitoring on Web (Next.js).",
      "Demonstrate see all rescue cases with an approved applicant in the Rescues tab.",
      "Verify: Views all active rescues with an approved applicant in the rescues tab."
    ],
    "vivaInsight": "Explain how rescue case monitoring operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/admin/rescues",
      "GET /api/v1/admin/rescues/map"
    ],
    "screenshots": [
      {
        "caption": "Rescue case monitoring view on Web (Next.js)",
        "placeholder": "/screenshots/administrator/administrator-09-main.png"
      }
    ]
  },
  {
    "id": "administrator-10",
    "role": "administrator",
    "userStory": "As an administrator, I want to override a rescue case back to Active so the original poster can select a different applicant if needed.",
    "functionality": "Rescue case override",
    "description": "Reverts a fostered rescue case back to active status to allow new applicant selection.",
    "platform": "Web (Next.js)",
    "demoSteps": [
      "Navigate to Rescue case override on Web (Next.js).",
      "Demonstrate override a rescue case back to Active.",
      "Verify: Reverts a fostered rescue case back to active status to allow new applicant selection."
    ],
    "vivaInsight": "Explain how rescue case override operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/posts/{postId}/rescue-applications/{applicationId}/admin-override",
      "PATCH /api/v1/admin/rescues/{postId}/urgency"
    ],
    "screenshots": [
      {
        "caption": "Rescue case override view on Web (Next.js)",
        "placeholder": "/screenshots/administrator/administrator-10-main.png"
      }
    ]
  },
  {
    "id": "administrator-11",
    "role": "administrator",
    "userStory": "As an administrator, I want to view all transport tasks and their statuses in the Transports tab so I can monitor animal movement across cases.",
    "functionality": "Transport task monitoring",
    "description": "Views all transport tasks and their statuses across the platform.",
    "platform": "Web (Next.js)",
    "demoSteps": [
      "Navigate to Transport task monitoring on Web (Next.js).",
      "Demonstrate view all transport tasks and their statuses in the Transports tab.",
      "Verify: Views all transport tasks and their statuses across the platform."
    ],
    "vivaInsight": "Explain how transport task monitoring operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/community/transport-tasks/admin",
      "GET /api/v1/community/transport-tasks/{id}"
    ],
    "screenshots": [
      {
        "caption": "Transport task monitoring view on Web (Next.js)",
        "placeholder": "/screenshots/administrator/administrator-11-main.png"
      }
    ]
  },
  {
    "id": "administrator-12",
    "role": "administrator",
    "userStory": "As an administrator, I want to review pending sponsorship requests in the Sponsorships tab and approve or reject them with an optional note so only legitimate requests appear in the community feed.",
    "functionality": "Sponsorship review",
    "description": "Approves or rejects pending sponsorship requests before they appear in the community feed.",
    "platform": "Web (Next.js)",
    "demoSteps": [
      "Navigate to Sponsorship review on Web (Next.js).",
      "Demonstrate review pending sponsorship requests in the Sponsorships tab and approve or reject them with an optional note.",
      "Verify: Approves or rejects pending sponsorship requests before they appear in the community feed."
    ],
    "vivaInsight": "Explain how sponsorship review operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/community/sponsorships/admin",
      "POST /api/v1/community/sponsorships/{id}/admin-review"
    ],
    "screenshots": [
      {
        "caption": "Sponsorship review view on Web (Next.js)",
        "placeholder": "/screenshots/administrator/administrator-12-main.png"
      }
    ]
  },
  {
    "id": "administrator-13",
    "role": "administrator",
    "userStory": "As an administrator, I want to download sponsorship proof documents so I can verify a request is legitimate before approving it.",
    "functionality": "Proof document verification",
    "description": "Downloads and reviews private proof documents attached to a sponsorship request.",
    "platform": "Web (Next.js)",
    "demoSteps": [
      "Navigate to Proof document verification on Web (Next.js).",
      "Demonstrate download sponsorship proof documents.",
      "Verify: Downloads and reviews private proof documents attached to a sponsorship request."
    ],
    "vivaInsight": "Explain how proof document verification operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/community/sponsorships/{id}/proof-documents"
    ],
    "screenshots": [
      {
        "caption": "Proof document verification view on Web (Next.js)",
        "placeholder": "/screenshots/administrator/administrator-13-main.png"
      }
    ]
  },
  {
    "id": "administrator-14",
    "role": "administrator",
    "userStory": "As an administrator, I want to moderate community posts by soft-deleting inappropriate content from the Community tab.",
    "functionality": "Community moderation",
    "description": "Soft-deletes inappropriate community posts from the dashboard.",
    "platform": "Web (Next.js)",
    "demoSteps": [
      "Navigate to Community moderation on Web (Next.js).",
      "Demonstrate moderate community posts by soft-deleting inappropriate content from the Community tab..",
      "Verify: Soft-deletes inappropriate community posts from the dashboard."
    ],
    "vivaInsight": "Explain how community moderation operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/admin/posts",
      "POST /api/v1/admin/posts/{postId}/restore",
      "DELETE /api/v1/admin/posts/{postId}/permanent"
    ],
    "screenshots": [
      {
        "caption": "Community moderation view on Web (Next.js)",
        "placeholder": "/screenshots/administrator/administrator-14-main.png"
      }
    ]
  },
  {
    "id": "adopter-01",
    "role": "adopter",
    "userStory": "As a user, I want to register for an account so I can join the platform.",
    "functionality": "Registration",
    "description": "Creates an account. Every user is signed up as an adopter initially.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Registration on Mobile (Flutter).",
      "Demonstrate register for an account.",
      "Verify: Creates an account. Every user is signed up as an adopter initially."
    ],
    "vivaInsight": "Explain how registration operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/auth/register/send-code",
      "POST /api/auth/register/verify-code",
      "POST /api/auth/register/complete"
    ],
    "screenshots": [
      {
        "caption": "Registration view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-01-main.png"
      }
    ]
  },
  {
    "id": "adopter-02",
    "role": "adopter",
    "userStory": "As a user, I want to assign myself roles in my dashboard so I can access features like fostering or transporting.",
    "functionality": "Role assignment",
    "description": "Assigns additional roles from the application dashboard later. Roles requiring KYC verification require submitting KYC documents.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Role assignment on Mobile (Flutter).",
      "Demonstrate assign myself roles in my dashboard.",
      "Verify: Assigns additional roles from the application dashboard later. Roles requiring KYC verification require submitting KYC documents."
    ],
    "vivaInsight": "Explain how role assignment operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/profile",
      "PUT /api/profile/roles/visibility"
    ],
    "screenshots": [
      {
        "caption": "Role assignment view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-02/step-01-profile-menu.png"
      }
    ]
  },
  {
    "id": "adopter-03",
    "role": "adopter",
    "userStory": "As a user, I want to sign in securely so I can access my dashboard and data.",
    "functionality": "Login and authentication",
    "description": "Signs in securely, with role-based access enforced through JWT so the session only exposes adopter-facing screens and data.",
    "platform": "Cross-platform",
    "demoSteps": [
      "Navigate to Login and authentication on Cross-platform.",
      "Demonstrate sign in securely.",
      "Verify: Signs in securely, with role-based access enforced through JWT so the session only exposes adopter-facing screens and data."
    ],
    "vivaInsight": "Explain how login and authentication operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/auth/mobile/login",
      "POST /api/auth/refresh",
      "GET /api/auth/me"
    ],
    "screenshots": [
      {
        "caption": "Login and authentication view on Cross-platform",
        "placeholder": "/screenshots/adopter/adopter-03/step-01-welcome-screen.png"
      }
    ]
  },
  {
    "id": "adopter-04",
    "role": "adopter",
    "userStory": "As a user, I want to submit my identity documents so I can become a verified user.",
    "functionality": "Identity verification (KYC)",
    "description": "Submits a national identity document that an administrator reviews and approves through the web panel before the account can list, apply, or message freely.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Identity verification (KYC) on Mobile (Flutter).",
      "Demonstrate submit my identity documents.",
      "Verify: Submits a national identity document that an administrator reviews and approves through the web panel before the account can list, apply, or message freely."
    ],
    "vivaInsight": "Explain how identity verification (kyc) operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/verification/status",
      "POST /api/verification/upload",
      "POST /api/verification/submit"
    ],
    "screenshots": [
      {
        "caption": "Identity verification (KYC) view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-04/step-01-profile-menu.png"
      }
    ]
  },
  {
    "id": "adopter-05",
    "role": "adopter",
    "userStory": "As an adopter, I want to complete a lifestyle profile so I can receive animal suggestions that fit my lifestyle.",
    "functionality": "Lifestyle profile and matching",
    "description": "Completes a short profile covering home size, activity level, and existing pets, and receives animal suggestions from a rule-based matching engine built on that profile.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Lifestyle profile and matching on Mobile (Flutter).",
      "Demonstrate complete a lifestyle profile.",
      "Verify: Completes a short profile covering home size, activity level, and existing pets, and receives animal suggestions from a rule-based matching engine built on that profile."
    ],
    "vivaInsight": "Explain how lifestyle profile and matching operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/profile/lifestyle",
      "PUT /api/profile/lifestyle"
    ],
    "screenshots": [
      {
        "caption": "Lifestyle profile and matching view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-05/step-01-profile-menu.png"
      }
    ]
  },
  {
    "id": "adopter-06",
    "role": "adopter",
    "userStory": "As an adopter, I want to browse and search adoption listings so I can find an animal to adopt.",
    "functionality": "Browse and search adoption listings",
    "description": "Searches and filters listed animals by species, location, and urgency, independent of any suggestion the matching engine has already made.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Open the search screen from the top navigation bar to access the animal discovery hub.",
      "Type a keyword query into the search bar to find matching animals by name, species, description, or location with debounced execution.",
      "Select quick filter chips or open the multi-criteria filter modal to filter by species, urgency level, and listing type.",
      "Apply filters and inspect matching animal listings, verifying that browsing operates independent of lifestyle profile suggestions.",
      "Test clearing and dismissing active filters to verify instant search state recovery."
    ],
    "vivaInsight": "Search operates independently of the lifestyle matching engine to give adopters unconstrained discovery. The backend uses EF Core queries with case-insensitive matching across post content, species, location, urgency enums, and spatial distance checks. Results carry an informational recommendation flag calculated against the user's lifestyle profile, while the mobile client isolates search state inside a dedicated controller to avoid mutating the primary community feed.",
    "endpoints": [
      "GET /api/v1/community/search",
      "GET /api/v1/community/posts/search",
      "GET /api/v1/community/posts",
      "GET /api/v1/community/posts/nearby"
    ],
    "screenshots": [
      {
        "caption": "Search exploration landing view with quick filter chips and suggestion cards",
        "placeholder": "/screenshots/adopter/adopter-06/step-01-search-explore.png"
      },
      {
        "caption": "Real-time debounced keyword search across animal names, breeds, and descriptions",
        "placeholder": "/screenshots/adopter/adopter-06/step-02-keyword-search.png"
      },
      {
        "caption": "Multi-criteria filter modal for species, listing type, urgency level, and location",
        "placeholder": "/screenshots/adopter/adopter-06/step-03-filter-modal-options.png"
      },
      {
        "caption": "Filtered animal listings independent of lifestyle profile suggestions with active filter tags",
        "placeholder": "/screenshots/adopter/adopter-06/step-04-filtered-results-independent.png"
      },
      {
        "caption": "Friendly empty state when no animals match with quick filter reset action",
        "placeholder": "/screenshots/adopter/adopter-06/step-05-empty-state-reset.png"
      }
    ]
  },
  {
    "id": "adopter-07",
    "role": "adopter",
    "userStory": "As an owner, I want to post my own animal for rehoming so I can find them a new home.",
    "functionality": "Adoption listing (owner)",
    "description": "An existing owner posts their own animal for rehoming with photos and a description, using the same listing flow an administrator can moderate.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Adoption listing (owner) on Mobile (Flutter).",
      "Demonstrate post my own animal for rehoming.",
      "Verify: An existing owner posts their own animal for rehoming with photos and a description, using the same listing flow an administrator can moderate."
    ],
    "vivaInsight": "Explain how adoption listing (owner) operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/posts",
      "GET /api/v1/community/posts/{id}"
    ],
    "screenshots": [
      {
        "caption": "Adoption listing (owner) view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-07-main.png"
      }
    ]
  },
  {
    "id": "adopter-08",
    "role": "adopter",
    "userStory": "As an adopter, I want to submit and track an adoption application so I can adopt a listed animal.",
    "functionality": "Submit and track an adoption application",
    "description": "Applies to adopt a listed animal and follows the application through pending, accepted, or declined status from the same screen.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Submit and track an adoption application on Mobile (Flutter).",
      "Demonstrate submit and track an adoption application.",
      "Verify: Applies to adopt a listed animal and follows the application through pending, accepted, or declined status from the same screen."
    ],
    "vivaInsight": "Explain how submit and track an adoption application operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/posts/{postId}/rescue-applications",
      "GET /api/v1/community/posts/{postId}/rescue-applications"
    ],
    "screenshots": [
      {
        "caption": "Submit and track an adoption application view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-08-main.png"
      }
    ]
  },
  {
    "id": "adopter-09",
    "role": "adopter",
    "userStory": "As a user, I want to photograph an injured or stray animal and report it so responders can help.",
    "functionality": "Rescue reporting",
    "description": "Photographs an injured or stray animal encountered in the field while the app captures the device’s GPS location automatically, and submits the report for triage.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Rescue reporting on Mobile (Flutter).",
      "Demonstrate photograph an injured or stray animal and report it.",
      "Verify: Photographs an injured or stray animal encountered in the field while the app captures the device’s GPS location automatically, and submits the report for triage."
    ],
    "vivaInsight": "Explain how rescue reporting operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/posts",
      "POST /api/v1/community/rescue-triage/assess"
    ],
    "screenshots": [
      {
        "caption": "Rescue reporting view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-09-main.png"
      }
    ]
  },
  {
    "id": "adopter-10",
    "role": "adopter",
    "userStory": "As a user, I want to message others privately in the app so I can communicate without sharing my phone number.",
    "functionality": "Private in-app messaging",
    "description": "Communicates with a foster, owner, or administrator through encrypted in-app chat built on SignalR, without exchanging a phone number.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Private in-app messaging on Mobile (Flutter).",
      "Demonstrate message others privately in the app.",
      "Verify: Communicates with a foster, owner, or administrator through encrypted in-app chat built on SignalR, without exchanging a phone number."
    ],
    "vivaInsight": "Explain how private in-app messaging operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/messaging/threads",
      "POST /api/messaging/threads/direct/{targetUserId}",
      "POST /api/messaging/threads/direct/{targetUserId}/messages",
      "GET /api/messaging/threads/{id}/messages"
    ],
    "screenshots": [
      {
        "caption": "Private in-app messaging view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-10-main.png"
      }
    ]
  },
  {
    "id": "adopter-11",
    "role": "adopter",
    "userStory": "As a user, I want to earn reputation and trust badges so others can trust my history on the platform.",
    "functionality": "Reputation and trust badges",
    "description": "Accumulates reputation points and visible trust badges from confirmed activity such as a completed adoption or a verified rescue report.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Reputation and trust badges on Mobile (Flutter).",
      "Demonstrate earn reputation and trust badges.",
      "Verify: Accumulates reputation points and visible trust badges from confirmed activity such as a completed adoption or a verified rescue report."
    ],
    "vivaInsight": "Explain how reputation and trust badges operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/profile/public/{userId}"
    ],
    "screenshots": [
      {
        "caption": "Reputation and trust badges view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-11-main.png"
      }
    ]
  },
  {
    "id": "adopter-12",
    "role": "adopter",
    "userStory": "As a user, I want to receive push notifications so I know about new messages and status changes.",
    "functionality": "Notifications",
    "description": "Receives push alerts, through Firebase Cloud Messaging, for new messages, application status changes, and nearby rescue cases that need a verified responder.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Notifications on Mobile (Flutter).",
      "Demonstrate receive push notifications.",
      "Verify: Receives push alerts, through Firebase Cloud Messaging, for new messages, application status changes, and nearby rescue cases that need a verified responder."
    ],
    "vivaInsight": "Explain how notifications operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/messaging/unread-count"
    ],
    "screenshots": [
      {
        "caption": "Notifications view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-12-main.png"
      }
    ]
  },
  {
    "id": "adopter-13",
    "role": "adopter",
    "userStory": "As an adopter, I want to submit an \"Apply to Rescue\" application on a Rescue post so I can offer to adopt the animal in need.",
    "functionality": "Apply to rescue",
    "description": "Submits an application to adopt a rescued animal directly from a rescue post.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Apply to rescue on Mobile (Flutter).",
      "Demonstrate submit an \"Apply to Rescue\" application on a Rescue post.",
      "Verify: Submits an application to adopt a rescued animal directly from a rescue post."
    ],
    "vivaInsight": "Explain how apply to rescue operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/posts/{postId}/rescue-applications"
    ],
    "screenshots": [
      {
        "caption": "Apply to rescue view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-13-main.png"
      }
    ]
  },
  {
    "id": "adopter-14",
    "role": "adopter",
    "userStory": "As an adopter, I want to see all my approved rescue cases in \"My Rescues\" so I can track each animal I have committed to.",
    "functionality": "My rescues tracking",
    "description": "Views a list of all approved rescue applications in the profile section.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to My rescues tracking on Mobile (Flutter).",
      "Demonstrate see all my approved rescue cases in \"My Rescues\".",
      "Verify: Views a list of all approved rescue applications in the profile section."
    ],
    "vivaInsight": "Explain how my rescues tracking operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/community/my-rescues"
    ],
    "screenshots": [
      {
        "caption": "My rescues tracking view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-14-main.png"
      }
    ]
  },
  {
    "id": "adopter-15",
    "role": "adopter",
    "userStory": "As an adopter, I want to confirm that a transporter has delivered the animal to me so the transport task is marked complete.",
    "functionality": "Delivery confirmation",
    "description": "Confirms receipt of an animal from a transporter to close the transport task.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Delivery confirmation on Mobile (Flutter).",
      "Demonstrate confirm that a transporter has delivered the animal to me.",
      "Verify: Confirms receipt of an animal from a transporter to close the transport task."
    ],
    "vivaInsight": "Explain how delivery confirmation operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/transport-tasks/{taskId}/confirm-delivery"
    ],
    "screenshots": [
      {
        "caption": "Delivery confirmation view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-15-main.png"
      }
    ]
  },
  {
    "id": "adopter-16",
    "role": "adopter",
    "userStory": "As an adopter, I want to post a Highlight to share a happy moment with my adopted pet so the community can celebrate with me.",
    "functionality": "Highlight posts",
    "description": "Shares photos and stories of an adopted pet with the community.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Highlight posts on Mobile (Flutter).",
      "Demonstrate post a Highlight to share a happy moment with my adopted pet.",
      "Verify: Shares photos and stories of an adopted pet with the community."
    ],
    "vivaInsight": "Explain how highlight posts operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/posts/{id}/like"
    ],
    "screenshots": [
      {
        "caption": "Highlight posts view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-16-main.png"
      }
    ]
  },
  {
    "id": "adopter-17",
    "role": "adopter",
    "userStory": "As an adopter, I want to post a Find Home listing for a pet I own so I can find it a new home.",
    "functionality": "Rehoming listing",
    "description": "Posts a Find Home listing for an owned pet directly to the community feed.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Rehoming listing on Mobile (Flutter).",
      "Demonstrate post a Find Home listing for a pet I own.",
      "Verify: Posts a Find Home listing for an owned pet directly to the community feed."
    ],
    "vivaInsight": "Explain how rehoming listing operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/posts",
      "GET /api/v1/community/posts/me"
    ],
    "screenshots": [
      {
        "caption": "Rehoming listing view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-17-main.png"
      }
    ]
  },
  {
    "id": "adopter-18",
    "role": "adopter",
    "userStory": "As an adopter, I want to post a Treatment request when my pet needs vet care so I can communicate the need to the community.",
    "functionality": "Vet care requests",
    "description": "Posts a treatment request to seek veterinary care support.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Vet care requests on Mobile (Flutter).",
      "Demonstrate post a Treatment request when my pet needs vet care.",
      "Verify: Posts a treatment request to seek veterinary care support."
    ],
    "vivaInsight": "Explain how vet care requests operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/posts",
      "GET /api/v1/community/posts/{id}"
    ],
    "screenshots": [
      {
        "caption": "Vet care requests view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-18-main.png"
      }
    ]
  },
  {
    "id": "adopter-19",
    "role": "adopter",
    "userStory": "As an adopter, I want to post a Sponsorship request when I cannot cover an animal's care costs so I can seek community support.",
    "functionality": "Sponsorship requests",
    "description": "Posts a funding request with proof documents to seek financial support for an animal.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Sponsorship requests on Mobile (Flutter).",
      "Demonstrate post a Sponsorship request when I cannot cover an animal's care costs.",
      "Verify: Posts a funding request with proof documents to seek financial support for an animal."
    ],
    "vivaInsight": "Explain how sponsorship requests operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/sponsorships",
      "GET /api/v1/community/posts/{id}"
    ],
    "screenshots": [
      {
        "caption": "Sponsorship requests view on Mobile (Flutter)",
        "placeholder": "/screenshots/adopter/adopter-19-main.png"
      }
    ]
  },
  {
    "id": "foster-01",
    "role": "foster",
    "userStory": "As a foster, I want to log in to my foster-facing screens so I can manage cases and messaging.",
    "functionality": "Login and authentication",
    "description": "Signs in securely with role-scoped, JWT-enforced access to foster-facing case and messaging screens.",
    "platform": "Cross-platform",
    "demoSteps": [
      "Navigate to Login and authentication on Cross-platform.",
      "Demonstrate log in to my foster-facing screens.",
      "Verify: Signs in securely with role-scoped, JWT-enforced access to foster-facing case and messaging screens."
    ],
    "vivaInsight": "Explain how login and authentication operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/auth/mobile/login",
      "GET /api/auth/me"
    ],
    "screenshots": [
      {
        "caption": "Login and authentication view on Cross-platform",
        "placeholder": "/screenshots/foster/foster-01-main.png"
      }
    ]
  },
  {
    "id": "foster-02",
    "role": "foster",
    "userStory": "As a foster, I want to submit my identity document for review so I can accept placements and receive alerts.",
    "functionality": "Identity verification (KYC)",
    "description": "Submits an identity document for administrator review before the account can accept a placement or receive geo-targeted alerts.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Identity verification (KYC) on Mobile (Flutter).",
      "Demonstrate submit my identity document for review.",
      "Verify: Submits an identity document for administrator review before the account can accept a placement or receive geo-targeted alerts."
    ],
    "vivaInsight": "Explain how identity verification (kyc) operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/verification/status",
      "POST /api/verification/upload",
      "POST /api/verification/submit"
    ],
    "screenshots": [
      {
        "caption": "Identity verification (KYC) view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-02-main.png"
      }
    ]
  },
  {
    "id": "foster-03",
    "role": "foster",
    "userStory": "As a foster, I want to receive geo-targeted rescue alerts so I can help when a nearby animal needs a temporary foster placement.",
    "functionality": "Geo-targeted rescue alerts",
    "description": "Receives a push notification, through Firebase Cloud Messaging, when a nearby triaged case needs a temporary foster placement.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Geo-targeted rescue alerts on Mobile (Flutter).",
      "Demonstrate receive geo-targeted rescue alerts.",
      "Verify: Receives a push notification, through Firebase Cloud Messaging, when a nearby triaged case needs a temporary foster placement."
    ],
    "vivaInsight": "Explain how geo-targeted rescue alerts operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/community/posts/nearby",
      "GET /api/v1/community/posts/map-bounds"
    ],
    "screenshots": [
      {
        "caption": "Geo-targeted rescue alerts view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-03-main.png"
      }
    ]
  },
  {
    "id": "foster-04",
    "role": "foster",
    "userStory": "As a foster, I want to photograph and report injured or stray animals so they can be triaged.",
    "functionality": "Rescue reporting",
    "description": "Photographs of an injured or stray animal found while out, with the device recording the location automatically for triage.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Rescue reporting on Mobile (Flutter).",
      "Demonstrate photograph and report injured or stray animals.",
      "Verify: Photographs of an injured or stray animal found while out, with the device recording the location automatically for triage."
    ],
    "vivaInsight": "Explain how rescue reporting operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/posts",
      "POST /api/v1/community/rescue-triage/assess"
    ],
    "screenshots": [
      {
        "caption": "Rescue reporting view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-04-main.png"
      }
    ]
  },
  {
    "id": "foster-05",
    "role": "foster",
    "userStory": "As a foster, I want to accept a referred rescue case so I can update the animal's condition and foster status.",
    "functionality": "Foster placement acceptance and case handling",
    "description": "Accepts a rescue case referred to them, views the case on the live map and case screen, and updates the animal’s condition and foster status as it changes.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Foster placement acceptance and case handling on Mobile (Flutter).",
      "Demonstrate accept a referred rescue case.",
      "Verify: Accepts a rescue case referred to them, views the case on the live map and case screen, and updates the animal’s condition and foster status as it changes."
    ],
    "vivaInsight": "Explain how foster placement acceptance and case handling operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/posts/{postId}/rescue-applications/{applicationId}/review",
      "GET /api/v1/community/posts/{postId}/rescue-applications"
    ],
    "screenshots": [
      {
        "caption": "Foster placement acceptance and case handling view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-05-main.png"
      }
    ]
  },
  {
    "id": "foster-06",
    "role": "foster",
    "userStory": "As a foster, I want to transition a fostered animal to an adoption listing so they can be rehomed.",
    "functionality": "Transition to adoption listing",
    "description": "Once a fostered animal is ready to be rehomed, creates or hands off an adoption listing so the adoption hub can match it with an adopter.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Transition to adoption listing on Mobile (Flutter).",
      "Demonstrate transition a fostered animal to an adoption listing.",
      "Verify: Once a fostered animal is ready to be rehomed, creates or hands off an adoption listing so the adoption hub can match it with an adopter."
    ],
    "vivaInsight": "Explain how transition to adoption listing operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/posts",
      "GET /api/v1/community/posts/{id}"
    ],
    "screenshots": [
      {
        "caption": "Transition to adoption listing view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-06-main.png"
      }
    ]
  },
  {
    "id": "foster-07",
    "role": "foster",
    "userStory": "As a foster, I want to use private in-app messaging to coordinate handover timing so I do not have to share my phone number.",
    "functionality": "Private in-app messaging",
    "description": "Coordinates handover timing and animal condition with transporters, veterinarians, and prospective adopters through encrypted in-app chat, without sharing a phone number.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Private in-app messaging on Mobile (Flutter).",
      "Demonstrate use private in-app messaging to coordinate handover timing.",
      "Verify: Coordinates handover timing and animal condition with transporters, veterinarians, and prospective adopters through encrypted in-app chat, without sharing a phone number."
    ],
    "vivaInsight": "Explain how private in-app messaging operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/messaging/threads",
      "POST /api/messaging/threads/direct/{targetUserId}/messages"
    ],
    "screenshots": [
      {
        "caption": "Private in-app messaging view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-07-main.png"
      }
    ]
  },
  {
    "id": "foster-08",
    "role": "foster",
    "userStory": "As a foster, I want to earn reputation and trust badges from my foster placements so adopters and administrators can trust me.",
    "functionality": "Reputation and trust badges",
    "description": "Builds reputation and a visible trust badge from completed foster placements and verified rescue reports.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Reputation and trust badges on Mobile (Flutter).",
      "Demonstrate earn reputation and trust badges from my foster placements.",
      "Verify: Builds reputation and a visible trust badge from completed foster placements and verified rescue reports."
    ],
    "vivaInsight": "Explain how reputation and trust badges operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/profile/public/{userId}"
    ],
    "screenshots": [
      {
        "caption": "Reputation and trust badges view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-08-main.png"
      }
    ]
  },
  {
    "id": "foster-09",
    "role": "foster",
    "userStory": "As a foster, I want to receive notifications for new nearby cases and messages so I do not miss important updates.",
    "functionality": "Notifications",
    "description": "Receives alerts for new nearby cases, incoming messages, and status changes on an animal currently in their care.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Notifications on Mobile (Flutter).",
      "Demonstrate receive notifications for new nearby cases and messages.",
      "Verify: Receives alerts for new nearby cases, incoming messages, and status changes on an animal currently in their care."
    ],
    "vivaInsight": "Explain how notifications operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/messaging/unread-count"
    ],
    "screenshots": [
      {
        "caption": "Notifications view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-09-main.png"
      }
    ]
  },
  {
    "id": "foster-10",
    "role": "foster",
    "userStory": "As a foster, I want to submit an \"Apply to Rescue\" application so I can offer to foster an animal in distress.",
    "functionality": "Apply to rescue",
    "description": "Submits an application to foster a rescued animal directly from a rescue post.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Apply to rescue on Mobile (Flutter).",
      "Demonstrate submit an \"Apply to Rescue\" application.",
      "Verify: Submits an application to foster a rescued animal directly from a rescue post."
    ],
    "vivaInsight": "Explain how apply to rescue operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/posts/{postId}/rescue-applications"
    ],
    "screenshots": [
      {
        "caption": "Apply to rescue view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-10-main.png"
      }
    ]
  },
  {
    "id": "foster-11",
    "role": "foster",
    "userStory": "As a foster, I want to post Update posts linked to my active rescue case so the community stays informed about the animal's progress.",
    "functionality": "Case updates",
    "description": "Posts progress updates that link back to the original rescue post.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Case updates on Mobile (Flutter).",
      "Demonstrate post Update posts linked to my active rescue case.",
      "Verify: Posts progress updates that link back to the original rescue post."
    ],
    "vivaInsight": "Explain how case updates operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/community/posts/{id}",
      "GET /api/v1/community/posts/me"
    ],
    "screenshots": [
      {
        "caption": "Case updates view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-11-main.png"
      }
    ]
  },
  {
    "id": "foster-12",
    "role": "foster",
    "userStory": "As a foster, I want to post a Transport request linked to my rescue case so I can find a transporter to move the animal.",
    "functionality": "Transport requests",
    "description": "Requests a transporter to move an animal linked to an active rescue case.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Transport requests on Mobile (Flutter).",
      "Demonstrate post a Transport request linked to my rescue case.",
      "Verify: Requests a transporter to move an animal linked to an active rescue case."
    ],
    "vivaInsight": "Explain how transport requests operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/transport-tasks",
      "GET /api/v1/community/transport-tasks/{id}"
    ],
    "screenshots": [
      {
        "caption": "Transport requests view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-12-main.png"
      }
    ]
  },
  {
    "id": "foster-13",
    "role": "foster",
    "userStory": "As a foster, I want to mark an animal as self-collected when I have my own vehicle so the system records the collection without needing a transporter.",
    "functionality": "Self-collection",
    "description": "Marks a transport task as completed through self-collection.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Self-collection on Mobile (Flutter).",
      "Demonstrate mark an animal as self-collected when I have my own vehicle.",
      "Verify: Marks a transport task as completed through self-collection."
    ],
    "vivaInsight": "Explain how self-collection operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/transport-tasks/{taskId}/mark-self-collected"
    ],
    "screenshots": [
      {
        "caption": "Self-collection view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-13-main.png"
      }
    ]
  },
  {
    "id": "foster-14",
    "role": "foster",
    "userStory": "As a foster, I want to confirm that a transporter has delivered the animal so the transport task is marked complete.",
    "functionality": "Delivery confirmation",
    "description": "Confirms receipt of an animal from a transporter to close the transport task.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Delivery confirmation on Mobile (Flutter).",
      "Demonstrate confirm that a transporter has delivered the animal.",
      "Verify: Confirms receipt of an animal from a transporter to close the transport task."
    ],
    "vivaInsight": "Explain how delivery confirmation operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/transport-tasks/{taskId}/confirm-delivery"
    ],
    "screenshots": [
      {
        "caption": "Delivery confirmation view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-14-main.png"
      }
    ]
  },
  {
    "id": "foster-15",
    "role": "foster",
    "userStory": "As a foster, I want to close a rescue case once transport is complete so the case is marked as resolved.",
    "functionality": "Case resolution",
    "description": "Closes an active rescue case after all related transport is completed.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Case resolution on Mobile (Flutter).",
      "Demonstrate close a rescue case once transport is complete.",
      "Verify: Closes an active rescue case after all related transport is completed."
    ],
    "vivaInsight": "Explain how case resolution operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/transport-tasks/{taskId}/close-rescue"
    ],
    "screenshots": [
      {
        "caption": "Case resolution view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-15-main.png"
      }
    ]
  },
  {
    "id": "foster-16",
    "role": "foster",
    "userStory": "As a foster, I want to post a Treatment request for an animal in my care so I can seek vet visit support.",
    "functionality": "Vet care requests",
    "description": "Posts a treatment request to seek veterinary care support.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Vet care requests on Mobile (Flutter).",
      "Demonstrate post a Treatment request for an animal in my care.",
      "Verify: Posts a treatment request to seek veterinary care support."
    ],
    "vivaInsight": "Explain how vet care requests operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/posts",
      "GET /api/v1/community/posts/{id}"
    ],
    "screenshots": [
      {
        "caption": "Vet care requests view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-16-main.png"
      }
    ]
  },
  {
    "id": "foster-17",
    "role": "foster",
    "userStory": "As a foster, I want to post a Sponsorship request when care costs exceed my means so I can seek community funding.",
    "functionality": "Sponsorship requests",
    "description": "Posts a funding request with proof documents to seek financial support for an animal.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Sponsorship requests on Mobile (Flutter).",
      "Demonstrate post a Sponsorship request when care costs exceed my means.",
      "Verify: Posts a funding request with proof documents to seek financial support for an animal."
    ],
    "vivaInsight": "Explain how sponsorship requests operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/sponsorships",
      "GET /api/v1/community/posts/{id}"
    ],
    "screenshots": [
      {
        "caption": "Sponsorship requests view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-17-main.png"
      }
    ]
  },
  {
    "id": "foster-18",
    "role": "foster",
    "userStory": "As a foster, I want to see all my active rescue cases in \"My Rescues\" so I can manage them from one place.",
    "functionality": "My rescues tracking",
    "description": "Views a list of all active rescue cases in the profile section.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to My rescues tracking on Mobile (Flutter).",
      "Demonstrate see all my active rescue cases in \"My Rescues\".",
      "Verify: Views a list of all active rescue cases in the profile section."
    ],
    "vivaInsight": "Explain how my rescues tracking operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/community/my-rescues"
    ],
    "screenshots": [
      {
        "caption": "My rescues tracking view on Mobile (Flutter)",
        "placeholder": "/screenshots/foster/foster-18-main.png"
      }
    ]
  },
  {
    "id": "sponsor-01",
    "role": "sponsor",
    "userStory": "As a sponsor, I want to log in to my sponsorship screens so I can track my cases.",
    "functionality": "Login and authentication",
    "description": "Signs in securely with role-scoped, JWT-enforced access to sponsorship and case-tracking screens.",
    "platform": "Cross-platform",
    "demoSteps": [
      "Navigate to Login and authentication on Cross-platform.",
      "Demonstrate log in to my sponsorship screens.",
      "Verify: Signs in securely with role-scoped, JWT-enforced access to sponsorship and case-tracking screens."
    ],
    "vivaInsight": "Explain how login and authentication operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/auth/mobile/login",
      "GET /api/auth/me"
    ],
    "screenshots": [
      {
        "caption": "Login and authentication view on Cross-platform",
        "placeholder": "/screenshots/sponsor/sponsor-01-main.png"
      }
    ]
  },
  {
    "id": "sponsor-02",
    "role": "sponsor",
    "userStory": "As a sponsor, I want to submit my identity document for review so I can pledge support against a case or listing.",
    "functionality": "Identity verification (KYC)",
    "description": "Submits an identity document for administrator review before the account can pledge support against a case or listing.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Identity verification (KYC) on Mobile (Flutter).",
      "Demonstrate submit my identity document for review.",
      "Verify: Submits an identity document for administrator review before the account can pledge support against a case or listing."
    ],
    "vivaInsight": "Explain how identity verification (kyc) operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/verification/status",
      "POST /api/verification/upload",
      "POST /api/verification/submit"
    ],
    "screenshots": [
      {
        "caption": "Identity verification (KYC) view on Mobile (Flutter)",
        "placeholder": "/screenshots/sponsor/sponsor-02-main.png"
      }
    ]
  },
  {
    "id": "sponsor-03",
    "role": "sponsor",
    "userStory": "As a sponsor, I want to browse rescue cases and adoption listings so I can decide who or what to support.",
    "functionality": "Browse rescue cases and adoption listings",
    "description": "Views triaged rescue cases and adoption listings, including the AI urgency classification attached to each one, to decide who or what to support.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Browse rescue cases and adoption listings on Mobile (Flutter).",
      "Demonstrate browse rescue cases and adoption listings.",
      "Verify: Views triaged rescue cases and adoption listings, including the AI urgency classification attached to each one, to decide who or what to support."
    ],
    "vivaInsight": "Explain how browse rescue cases and adoption listings operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/community/posts",
      "GET /api/v1/community/posts/nearby"
    ],
    "screenshots": [
      {
        "caption": "Browse rescue cases and adoption listings view on Mobile (Flutter)",
        "placeholder": "/screenshots/sponsor/sponsor-03-main.png"
      }
    ]
  },
  {
    "id": "sponsor-04",
    "role": "sponsor",
    "userStory": "As a sponsor, I want to pledge support to a case or listing so I can record my sponsorship commitment.",
    "functionality": "Pledge support to a case or listing",
    "description": "Records a sponsorship commitment against a specific animal or case. In the three-week MVP this is a simulated pledge rather than a live transaction, consistent with the proposal’s decision to defer real payment processing to the post-MVP roadmap.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Pledge support to a case or listing on Mobile (Flutter).",
      "Demonstrate pledge support to a case or listing.",
      "Verify: Records a sponsorship commitment against a specific animal or case. In the three-week MVP this is a simulated pledge rather than a live transaction, consistent with the proposal’s decision to defer real payment processing to the post-MVP roadmap."
    ],
    "vivaInsight": "Explain how pledge support to a case or listing operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/sponsorships"
    ],
    "screenshots": [
      {
        "caption": "Pledge support to a case or listing view on Mobile (Flutter)",
        "placeholder": "/screenshots/sponsor/sponsor-04-main.png"
      }
    ]
  },
  {
    "id": "sponsor-05",
    "role": "sponsor",
    "userStory": "As a sponsor, I want to track sponsored case progress so I can see what happened after my pledge.",
    "functionality": "Track sponsored case progress",
    "description": "Follows status updates on an animal or case the sponsor has backed, from the same screen used to make the original pledge.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Track sponsored case progress on Mobile (Flutter).",
      "Demonstrate track sponsored case progress.",
      "Verify: Follows status updates on an animal or case the sponsor has backed, from the same screen used to make the original pledge."
    ],
    "vivaInsight": "Explain how track sponsored case progress operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/community/posts/{id}",
      "POST /api/v1/community/sponsorships/{id}/mark-funded"
    ],
    "screenshots": [
      {
        "caption": "Track sponsored case progress view on Mobile (Flutter)",
        "placeholder": "/screenshots/sponsor/sponsor-05-main.png"
      }
    ]
  },
  {
    "id": "sponsor-06",
    "role": "sponsor",
    "userStory": "As a sponsor, I want to contact the foster, veterinarian, or administrator through private in-app messaging so I can get an update without sharing a phone number.",
    "functionality": "Private in-app messaging",
    "description": "Contacts the foster, veterinarian, or administrator attached to a sponsored case for an update, without sharing a phone number.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Private in-app messaging on Mobile (Flutter).",
      "Demonstrate contact the foster, veterinarian, or administrator through private in-app messaging.",
      "Verify: Contacts the foster, veterinarian, or administrator attached to a sponsored case for an update, without sharing a phone number."
    ],
    "vivaInsight": "Explain how private in-app messaging operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/messaging/threads",
      "POST /api/messaging/threads/direct/{targetUserId}/messages"
    ],
    "screenshots": [
      {
        "caption": "Private in-app messaging view on Mobile (Flutter)",
        "placeholder": "/screenshots/sponsor/sponsor-06-main.png"
      }
    ]
  },
  {
    "id": "sponsor-07",
    "role": "sponsor",
    "userStory": "As a sponsor, I want to earn reputation and trust badges from my completed sponsorships so other users can see my support history.",
    "functionality": "Reputation and trust badges",
    "description": "Builds reputation and a visible trust badge from confirmed, completed sponsorships.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Reputation and trust badges on Mobile (Flutter).",
      "Demonstrate earn reputation and trust badges from my completed sponsorships.",
      "Verify: Builds reputation and a visible trust badge from confirmed, completed sponsorships."
    ],
    "vivaInsight": "Explain how reputation and trust badges operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/profile/public/{userId}"
    ],
    "screenshots": [
      {
        "caption": "Reputation and trust badges view on Mobile (Flutter)",
        "placeholder": "/screenshots/sponsor/sponsor-07-main.png"
      }
    ]
  },
  {
    "id": "sponsor-08",
    "role": "sponsor",
    "userStory": "As a sponsor, I want to receive notifications for updates on sponsored cases so I don't have to check back manually.",
    "functionality": "Notifications",
    "description": "Receives alerts for updates on sponsored cases and incoming messages.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Notifications on Mobile (Flutter).",
      "Demonstrate receive notifications for updates on sponsored cases.",
      "Verify: Receives alerts for updates on sponsored cases and incoming messages."
    ],
    "vivaInsight": "Explain how notifications operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/messaging/unread-count"
    ],
    "screenshots": [
      {
        "caption": "Notifications view on Mobile (Flutter)",
        "placeholder": "/screenshots/sponsor/sponsor-08-main.png"
      }
    ]
  },
  {
    "id": "transporter-01",
    "role": "transporter",
    "userStory": "As a transporter, I want to log in to my transport screens so I can manage my transport requests.",
    "functionality": "Login and authentication",
    "description": "Signs in securely with role-scoped, JWT-enforced access to transport requests and case screens.",
    "platform": "Cross-platform",
    "demoSteps": [
      "Navigate to Login and authentication on Cross-platform.",
      "Demonstrate log in to my transport screens.",
      "Verify: Signs in securely with role-scoped, JWT-enforced access to transport requests and case screens."
    ],
    "vivaInsight": "Explain how login and authentication operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/auth/mobile/login",
      "GET /api/auth/me"
    ],
    "screenshots": [
      {
        "caption": "Login and authentication view on Cross-platform",
        "placeholder": "/screenshots/transporter/transporter-01-main.png"
      }
    ]
  },
  {
    "id": "transporter-02",
    "role": "transporter",
    "userStory": "As a transporter, I want to submit my identity document for review so I can accept transport tasks.",
    "functionality": "Identity verification (KYC)",
    "description": "Submits an identity document for administrator review before the account can accept a transport task.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Identity verification (KYC) on Mobile (Flutter).",
      "Demonstrate submit my identity document for review.",
      "Verify: Submits an identity document for administrator review before the account can accept a transport task."
    ],
    "vivaInsight": "Explain how identity verification (kyc) operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/verification/status",
      "POST /api/verification/upload",
      "POST /api/verification/submit"
    ],
    "screenshots": [
      {
        "caption": "Identity verification (KYC) view on Mobile (Flutter)",
        "placeholder": "/screenshots/transporter/transporter-02-main.png"
      }
    ]
  },
  {
    "id": "transporter-03",
    "role": "transporter",
    "userStory": "As a transporter, I want to receive geo-targeted transport alerts so I know when an animal nearby needs to be moved.",
    "functionality": "Geo-targeted transport alerts",
    "description": "Receives a push notification when a nearby case needs an animal moved between a rescue site, a foster, a veterinarian, or an adopter.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Geo-targeted transport alerts on Mobile (Flutter).",
      "Demonstrate receive geo-targeted transport alerts.",
      "Verify: Receives a push notification when a nearby case needs an animal moved between a rescue site, a foster, a veterinarian, or an adopter."
    ],
    "vivaInsight": "Explain how geo-targeted transport alerts operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/community/posts/nearby",
      "GET /api/v1/community/transport-tasks/mine"
    ],
    "screenshots": [
      {
        "caption": "Geo-targeted transport alerts view on Mobile (Flutter)",
        "placeholder": "/screenshots/transporter/transporter-03-main.png"
      }
    ]
  },
  {
    "id": "transporter-04",
    "role": "transporter",
    "userStory": "As a transporter, I want to report an animal I find while en route so they can be triaged.",
    "functionality": "Rescue reporting",
    "description": "Reports an animal found while en route, with photo and automatic location capture feeding the same triage pipeline every other role uses.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Rescue reporting on Mobile (Flutter).",
      "Demonstrate report an animal I find while en route.",
      "Verify: Reports an animal found while en route, with photo and automatic location capture feeding the same triage pipeline every other role uses."
    ],
    "vivaInsight": "Explain how rescue reporting operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/posts",
      "POST /api/v1/community/rescue-triage/assess"
    ],
    "screenshots": [
      {
        "caption": "Rescue reporting view on Mobile (Flutter)",
        "placeholder": "/screenshots/transporter/transporter-04-main.png"
      }
    ]
  },
  {
    "id": "transporter-05",
    "role": "transporter",
    "userStory": "As a transporter, I want to accept and track a transport task so everyone knows the status of the animal in transit.",
    "functionality": "Accept and track a transport task",
    "description": "Claims an open transport request and updates its status through assigned, picked up, in transit, and delivered, which the administration panel’s case map reflects in real time.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Accept and track a transport task on Mobile (Flutter).",
      "Demonstrate accept and track a transport task.",
      "Verify: Claims an open transport request and updates its status through assigned, picked up, in transit, and delivered, which the administration panel’s case map reflects in real time."
    ],
    "vivaInsight": "Explain how accept and track a transport task operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/community/transport-tasks/{id}",
      "GET /api/v1/community/transport-tasks/mine"
    ],
    "screenshots": [
      {
        "caption": "Accept and track a transport task view on Mobile (Flutter)",
        "placeholder": "/screenshots/transporter/transporter-05-main.png"
      }
    ]
  },
  {
    "id": "transporter-06",
    "role": "transporter",
    "userStory": "As a transporter, I want to use private in-app messaging to coordinate pickup and drop-off timing so I don't have to share my phone number.",
    "functionality": "Private in-app messaging",
    "description": "Coordinates pickup and drop-off timing with fosters, veterinarians, and adopters through encrypted chat, without exchanging a phone number.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Private in-app messaging on Mobile (Flutter).",
      "Demonstrate use private in-app messaging to coordinate pickup and drop-off timing.",
      "Verify: Coordinates pickup and drop-off timing with fosters, veterinarians, and adopters through encrypted chat, without exchanging a phone number."
    ],
    "vivaInsight": "Explain how private in-app messaging operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/messaging/threads",
      "POST /api/messaging/threads/direct/{targetUserId}/messages"
    ],
    "screenshots": [
      {
        "caption": "Private in-app messaging view on Mobile (Flutter)",
        "placeholder": "/screenshots/transporter/transporter-06-main.png"
      }
    ]
  },
  {
    "id": "transporter-07",
    "role": "transporter",
    "userStory": "As a transporter, I want to earn reputation and trust badges from my verified transport runs so fosters and veterinarians trust me.",
    "functionality": "Reputation and trust badges",
    "description": "Builds reputation and a visible trust badge from completed, verified transport runs.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Reputation and trust badges on Mobile (Flutter).",
      "Demonstrate earn reputation and trust badges from my verified transport runs.",
      "Verify: Builds reputation and a visible trust badge from completed, verified transport runs."
    ],
    "vivaInsight": "Explain how reputation and trust badges operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/profile/public/{userId}"
    ],
    "screenshots": [
      {
        "caption": "Reputation and trust badges view on Mobile (Flutter)",
        "placeholder": "/screenshots/transporter/transporter-07-main.png"
      }
    ]
  },
  {
    "id": "transporter-08",
    "role": "transporter",
    "userStory": "As a transporter, I want to receive notifications for open transport requests nearby so I can respond quickly.",
    "functionality": "Notifications",
    "description": "Receives alerts for open transport requests nearby, new messages, and status updates on any case currently assigned to them.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Notifications on Mobile (Flutter).",
      "Demonstrate receive notifications for open transport requests nearby.",
      "Verify: Receives alerts for open transport requests nearby, new messages, and status updates on any case currently assigned to them."
    ],
    "vivaInsight": "Explain how notifications operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/messaging/unread-count"
    ],
    "screenshots": [
      {
        "caption": "Notifications view on Mobile (Flutter)",
        "placeholder": "/screenshots/transporter/transporter-08-main.png"
      }
    ]
  },
  {
    "id": "transporter-09",
    "role": "transporter",
    "userStory": "As a transporter, I want to submit an offer on a Transport post with my proposed pickup window so the requester can see my availability.",
    "functionality": "Transport offers",
    "description": "Submits an offer with a pickup window on an open transport request.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Transport offers on Mobile (Flutter).",
      "Demonstrate submit an offer on a Transport post with my proposed pickup window.",
      "Verify: Submits an offer with a pickup window on an open transport request."
    ],
    "vivaInsight": "Explain how transport offers operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/transport-tasks/{taskId}/offers"
    ],
    "screenshots": [
      {
        "caption": "Transport offers view on Mobile (Flutter)",
        "placeholder": "/screenshots/transporter/transporter-09-main.png"
      }
    ]
  },
  {
    "id": "transporter-10",
    "role": "transporter",
    "userStory": "As a transporter, I want to receive a notification when my transport offer is accepted so I know when to show up.",
    "functionality": "Offer acceptance alerts",
    "description": "Receives a push notification when a transport offer is accepted by the requester.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Offer acceptance alerts on Mobile (Flutter).",
      "Demonstrate receive a notification when my transport offer is accepted.",
      "Verify: Receives a push notification when a transport offer is accepted by the requester."
    ],
    "vivaInsight": "Explain how offer acceptance alerts operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/transport-tasks/{taskId}/offers/{offerId}/accept"
    ],
    "screenshots": [
      {
        "caption": "Offer acceptance alerts view on Mobile (Flutter)",
        "placeholder": "/screenshots/transporter/transporter-10-main.png"
      }
    ]
  },
  {
    "id": "transporter-11",
    "role": "transporter",
    "userStory": "As a transporter, I want to mark the transport as PickedUp, InTransit, and Delivered as I progress so the requester knows where the animal is.",
    "functionality": "Transport status updates",
    "description": "Updates the status of an active transport task through its lifecycle.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Transport status updates on Mobile (Flutter).",
      "Demonstrate mark the transport as PickedUp, InTransit, and Delivered as I progress.",
      "Verify: Updates the status of an active transport task through its lifecycle."
    ],
    "vivaInsight": "Explain how transport status updates operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "PATCH /api/v1/community/transport-tasks/{taskId}/status"
    ],
    "screenshots": [
      {
        "caption": "Transport status updates view on Mobile (Flutter)",
        "placeholder": "/screenshots/transporter/transporter-11-main.png"
      }
    ]
  },
  {
    "id": "transporter-12",
    "role": "transporter",
    "userStory": "As a transporter, I want to see all my transport tasks in \"My Transports\" so I can track my active and completed deliveries.",
    "functionality": "My transports tracking",
    "description": "Views a list of all active and completed transport tasks in the profile section.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to My transports tracking on Mobile (Flutter).",
      "Demonstrate see all my transport tasks in \"My Transports\".",
      "Verify: Views a list of all active and completed transport tasks in the profile section."
    ],
    "vivaInsight": "Explain how my transports tracking operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/community/transport-tasks/mine"
    ],
    "screenshots": [
      {
        "caption": "My transports tracking view on Mobile (Flutter)",
        "placeholder": "/screenshots/transporter/transporter-12-main.png"
      }
    ]
  },
  {
    "id": "veterinarian-01",
    "role": "veterinarian",
    "userStory": "As a veterinarian, I want to log in to my case review screens so I can manage my professional-facing access separately from my general user session.",
    "functionality": "Login and authentication",
    "description": "Signs in securely with role-scoped, JWT-enforced access to case review and messaging screens.",
    "platform": "Cross-platform",
    "demoSteps": [
      "Navigate to Login and authentication on Cross-platform.",
      "Demonstrate log in to my case review screens.",
      "Verify: Signs in securely with role-scoped, JWT-enforced access to case review and messaging screens."
    ],
    "vivaInsight": "Explain how login and authentication operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/auth/mobile/login",
      "GET /api/auth/me"
    ],
    "screenshots": [
      {
        "caption": "Login and authentication view on Cross-platform",
        "placeholder": "/screenshots/veterinarian/veterinarian-01-main.png"
      }
    ]
  },
  {
    "id": "veterinarian-02",
    "role": "veterinarian",
    "userStory": "As a veterinarian, I want to submit my clinic registration or professional license for review so my account can act as a verified veterinarian.",
    "functionality": "Identity verification (KYC)",
    "description": "Submits a clinic registration or professional license, rather than a general identity document, for administrator review before the account can act as a verified veterinarian.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Identity verification (KYC) on Mobile (Flutter).",
      "Demonstrate submit my clinic registration or professional license for review.",
      "Verify: Submits a clinic registration or professional license, rather than a general identity document, for administrator review before the account can act as a verified veterinarian."
    ],
    "vivaInsight": "Explain how identity verification (kyc) operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/verification/status",
      "POST /api/verification/upload",
      "POST /api/verification/submit"
    ],
    "screenshots": [
      {
        "caption": "Identity verification (KYC) view on Mobile (Flutter)",
        "placeholder": "/screenshots/veterinarian/veterinarian-02-main.png"
      }
    ]
  },
  {
    "id": "veterinarian-03",
    "role": "veterinarian",
    "userStory": "As a veterinarian, I want to receive geo-targeted rescue alerts when a nearby case needs medical attention.",
    "functionality": "Geo-targeted rescue alerts",
    "description": "Receives a push notification when a nearby case is classified as critical or moderate and needs medical attention.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Geo-targeted rescue alerts on Mobile (Flutter).",
      "Demonstrate receive geo-targeted rescue alerts when a nearby case needs medical attention..",
      "Verify: Receives a push notification when a nearby case is classified as critical or moderate and needs medical attention."
    ],
    "vivaInsight": "Explain how geo-targeted rescue alerts operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/v1/community/posts/nearby"
    ],
    "screenshots": [
      {
        "caption": "Geo-targeted rescue alerts view on Mobile (Flutter)",
        "placeholder": "/screenshots/veterinarian/veterinarian-03-main.png"
      }
    ]
  },
  {
    "id": "veterinarian-04",
    "role": "veterinarian",
    "userStory": "As a veterinarian, I want to review AI photo triage and confirm urgency so I can confirm or override it with my professional judgment.",
    "functionality": "Review AI photo triage and confirm urgency",
    "description": "Opens a reported case, reviews Gemini’s critical, moderate, or low classification against the submitted photo, and confirms or overrides it with a professional judgement.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Review AI photo triage and confirm urgency on Mobile (Flutter).",
      "Demonstrate review AI photo triage and confirm urgency.",
      "Verify: Opens a reported case, reviews Gemini’s critical, moderate, or low classification against the submitted photo, and confirms or overrides it with a professional judgement."
    ],
    "vivaInsight": "Explain how review ai photo triage and confirm urgency operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/rescue-triage/assess",
      "PATCH /api/v1/admin/rescues/{postId}/urgency"
    ],
    "screenshots": [
      {
        "caption": "Review AI photo triage and confirm urgency view on Mobile (Flutter)",
        "placeholder": "/screenshots/veterinarian/veterinarian-04-main.png"
      }
    ]
  },
  {
    "id": "veterinarian-05",
    "role": "veterinarian",
    "userStory": "As a veterinarian, I want to provide medical guidance so I can give treatment advice to the animal's foster, transporter, or owner.",
    "functionality": "Provide medical guidance",
    "description": "Responds to a case or a private message with treatment advice for the animal’s foster, transporter, or owner.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Provide medical guidance on Mobile (Flutter).",
      "Demonstrate provide medical guidance.",
      "Verify: Responds to a case or a private message with treatment advice for the animal’s foster, transporter, or owner."
    ],
    "vivaInsight": "Explain how provide medical guidance operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "POST /api/v1/community/posts",
      "POST /api/messaging/threads/direct/{targetUserId}/messages"
    ],
    "screenshots": [
      {
        "caption": "Provide medical guidance view on Mobile (Flutter)",
        "placeholder": "/screenshots/veterinarian/veterinarian-05-main.png"
      }
    ]
  },
  {
    "id": "veterinarian-06",
    "role": "veterinarian",
    "userStory": "As a veterinarian, I want to communicate directly with the user handling an animal through private in-app messaging to give guidance or ask for more information.",
    "functionality": "Private in-app messaging",
    "description": "Communicates directly with the user currently handling an animal, without a shared phone number, to give guidance or ask for more information.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Private in-app messaging on Mobile (Flutter).",
      "Demonstrate communicate directly with the user handling an animal through private in-app messaging to give guidance or ask for more information..",
      "Verify: Communicates directly with the user currently handling an animal, without a shared phone number, to give guidance or ask for more information."
    ],
    "vivaInsight": "Explain how private in-app messaging operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/messaging/threads",
      "POST /api/messaging/threads/direct/{targetUserId}/messages"
    ],
    "screenshots": [
      {
        "caption": "Private in-app messaging view on Mobile (Flutter)",
        "placeholder": "/screenshots/veterinarian/veterinarian-06-main.png"
      }
    ]
  },
  {
    "id": "veterinarian-07",
    "role": "veterinarian",
    "userStory": "As a veterinarian, I want to build reputation and earn an expert-verified badge so users can tell my advice apart from unverified comments.",
    "functionality": "Reputation and trust badges",
    "description": "Builds reputation and an expert-verified badge from confirmed medical input and completed case reviews.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Reputation and trust badges on Mobile (Flutter).",
      "Demonstrate build reputation and earn an expert-verified badge.",
      "Verify: Builds reputation and an expert-verified badge from confirmed medical input and completed case reviews."
    ],
    "vivaInsight": "Explain how reputation and trust badges operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/profile/public/{userId}"
    ],
    "screenshots": [
      {
        "caption": "Reputation and trust badges view on Mobile (Flutter)",
        "placeholder": "/screenshots/veterinarian/veterinarian-07-main.png"
      }
    ]
  },
  {
    "id": "veterinarian-08",
    "role": "veterinarian",
    "userStory": "As a veterinarian, I want to receive notifications for new nearby cases that need medical review so I can act quickly.",
    "functionality": "Notifications",
    "description": "Receives alerts for new nearby cases that need medical review and incoming messages.",
    "platform": "Mobile (Flutter)",
    "demoSteps": [
      "Navigate to Notifications on Mobile (Flutter).",
      "Demonstrate receive notifications for new nearby cases that need medical review.",
      "Verify: Receives alerts for new nearby cases that need medical review and incoming messages."
    ],
    "vivaInsight": "Explain how notifications operates within Clean Architecture and enforces role claims.",
    "endpoints": [
      "GET /api/messaging/unread-count"
    ],
    "screenshots": [
      {
        "caption": "Notifications view on Mobile (Flutter)",
        "placeholder": "/screenshots/veterinarian/veterinarian-08-main.png"
      }
    ]
  }
];

export function getStoriesByRole(roleId: string): UserStory[] {
  return USER_STORIES.filter(s => s.role.toLowerCase() === roleId.toLowerCase());
}

export function getStoryById(storyId: string): UserStory | undefined {
  return USER_STORIES.find(s => s.id.toLowerCase() === storyId.toLowerCase());
}

export function searchStories(query: string): UserStory[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  return USER_STORIES.filter(s => {
    return (
      s.functionality.toLowerCase().includes(q) ||
      s.userStory.toLowerCase().includes(q) ||
      s.id.toLowerCase().includes(q) ||
      s.role.toLowerCase().includes(q) ||
      s.description.toLowerCase().includes(q) ||
      s.platform.toLowerCase().includes(q)
    );
  }).slice(0, 10);
}
