// <auto-generated />
using System;
using System.Collections.Generic;
using HappyPaws.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HappyPaws.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HappyPaws.Domain.Entities.CanMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FromUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("boolean");

                    b.Property<long>("ToUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ToUserId");

                    b.HasIndex("FromUserId", "ToUserId")
                        .IsUnique();

                    b.ToTable("can_message", (string)null);
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.ChatParticipant", b =>
                {
                    b.Property<long>("ThreadId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ClearedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cleared_at");

                    b.Property<DateTimeOffset?>("LastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ThreadId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("chat_participants", (string)null);
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.ChatThread", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDirectMessage")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("chat_threads", (string)null);
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ThreadId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("ThreadId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiTriageReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("AnimalDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("animal_description");

                    b.Property<string>("AnimalName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("animal_name");

                    b.Property<string>("AnimalSpecies")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("animal_species");

                    b.Property<Guid?>("AssignedApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_application_id");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsUrgencyManuallyOverridden")
                        .HasColumnType("boolean");

                    b.Property<int>("LikeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("like_count");

                    b.Property<string>("LocationLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location_label");

                    b.Property<Point>("LocationPoint")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("location_point");

                    b.Property<Guid?>("ParentPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_post_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("UrgencyAssessedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UrgencyLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedApplicationId")
                        .IsUnique();

                    b.HasIndex("LocationPoint")
                        .HasDatabaseName("idx_posts_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LocationPoint"), "gist");

                    b.HasIndex("ParentPostId");

                    b.HasIndex("AuthorId", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("Type", "Status", "CreatedAt")
                        .IsDescending(false, false, true);

                    b.ToTable("posts", null, t =>
                        {
                            t.HasCheckConstraint("CK_posts_status", "status IN ('Active', 'Fostered', 'Assigned', 'Completed', 'PendingApproval', 'Funded', 'Rejected', 'Cancelled')");

                            t.HasCheckConstraint("CK_posts_type", "type IN ('RescueAlert', 'FosterUpdate', 'AdoptionListing', 'Highlight', 'TransportRequest', 'VetRequest', 'SponsorshipRequest')");
                        });
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.PostLike", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("LikedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("liked_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("post_likes", (string)null);
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.PostMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CdnUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cdn_url");

                    b.Property<int>("FileSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<short>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("sort_order");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PostId", "SortOrder");

                    b.ToTable("post_media", null, t =>
                        {
                            t.HasCheckConstraint("CK_post_media_file_size", "file_size_bytes <= 5242880");

                            t.HasCheckConstraint("CK_post_media_mime_type", "mime_type IN ('image/jpeg','image/png','image/webp','image/heic')");
                        });
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReasonRevoked")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.RescueApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AdminReviewedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("admin_reviewed_at");

                    b.Property<long?>("AdminReviewerId")
                        .HasColumnType("bigint")
                        .HasColumnName("admin_reviewer_id");

                    b.Property<long>("ApplicantId")
                        .HasColumnType("bigint")
                        .HasColumnName("applicant_id");

                    b.Property<string>("ApplicantRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("applicant_role");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExperienceSummary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("experience_summary");

                    b.Property<bool>("HasVehicle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_vehicle");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("PosterReviewedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("poster_reviewed_at");

                    b.Property<Guid>("RescuePostId")
                        .HasColumnType("uuid")
                        .HasColumnName("rescue_post_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AdminReviewerId");

                    b.HasIndex("ApplicantId", "Status");

                    b.HasIndex("RescuePostId", "Status");

                    b.ToTable("rescue_applications", null, t =>
                        {
                            t.HasCheckConstraint("CK_rescue_applications_role", "applicant_role IN ('Foster','Adopter')");

                            t.HasCheckConstraint("CK_rescue_applications_status", "status IN ('Pending','Approved','Rejected','AdminOverridden')");
                        });
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.SponsorshipDetails", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<long?>("AdminApproverId")
                        .HasColumnType("bigint")
                        .HasColumnName("admin_approver_id");

                    b.Property<string>("AdminRejectionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("admin_rejection_notes");

                    b.Property<DateTimeOffset?>("AdminReviewedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("admin_reviewed_at");

                    b.Property<decimal?>("EstimatedAmountLkr")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("estimated_amount_lkr");

                    b.Property<DateTimeOffset?>("FundedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("funded_at");

                    b.Property<string>("GoalDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("goal_description");

                    b.HasKey("PostId");

                    b.HasIndex("AdminApproverId");

                    b.ToTable("sponsorship_details", (string)null);
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.SponsorshipProofDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("file_name");

                    b.Property<int>("FileSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("sponsorship_proof_documents", null, t =>
                        {
                            t.HasCheckConstraint("CK_sponsorship_proof_file_size", "file_size_bytes <= 5242880");

                            t.HasCheckConstraint("CK_sponsorship_proof_mime_type", "mime_type IN ('image/jpeg','image/png','image/webp','image/heic','application/pdf')");
                        });
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.TransportOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("ProposedPickupEnd")
                        .HasColumnType("timestamptz")
                        .HasColumnName("proposed_pickup_end");

                    b.Property<DateTimeOffset>("ProposedPickupStart")
                        .HasColumnType("timestamptz")
                        .HasColumnName("proposed_pickup_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TransportTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_task_id");

                    b.Property<long>("TransporterId")
                        .HasColumnType("bigint")
                        .HasColumnName("transporter_id");

                    b.HasKey("Id");

                    b.HasIndex("TransporterId");

                    b.HasIndex("TransportTaskId", "Status");

                    b.ToTable("transport_offers", null, t =>
                        {
                            t.HasCheckConstraint("CK_transport_offers_status", "status IN ('Pending','Accepted','Rejected')");
                        });
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.TransportTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DropoffAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("dropoff_address");

                    b.Property<Point>("DropoffPoint")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("dropoff_point");

                    b.Property<bool>("IsSelfCollection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_self_collection");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ParentPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_post_id");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("pickup_address");

                    b.Property<Point>("PickupPoint")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("pickup_point");

                    b.Property<DateTimeOffset?>("PickupWindowEnd")
                        .HasColumnType("timestamptz")
                        .HasColumnName("pickup_window_end");

                    b.Property<DateTimeOffset?>("PickupWindowStart")
                        .HasColumnType("timestamptz")
                        .HasColumnName("pickup_window_start");

                    b.Property<long>("RequesterId")
                        .HasColumnType("bigint")
                        .HasColumnName("requester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("TransportPostId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_post_id");

                    b.Property<long?>("TransporterId")
                        .HasColumnType("bigint")
                        .HasColumnName("transporter_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ParentPostId");

                    b.HasIndex("PickupPoint");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PickupPoint"), "gist");

                    b.HasIndex("RequesterId");

                    b.HasIndex("TransportPostId");

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("TransporterId", "Status");

                    b.ToTable("transport_tasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_transport_tasks_status", "status IN ('Open','Accepted','PickedUp','InTransit','Delivered','Completed','Cancelled')");
                        });
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line2");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<double?>("HomeLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("home_latitude");

                    b.Property<double?>("HomeLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("home_longitude");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<bool>("ReceiveMessages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("receive_messages");

                    b.Property<int>("ReputationPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reputation_points");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Tagline")
                        .HasMaxLength(150)
                        .HasColumnType("text")
                        .HasColumnName("tagline");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_lower_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("idx_users_lower_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.UserBadge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BadgeType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.UserDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text")
                        .HasColumnName("device_type");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fcm_token");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_active_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_hash");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FcmToken")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_devices_user_id");

                    b.ToTable("user_devices", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_devices_device_type", "device_type IN ('ANDROID', 'IOS', 'WEB')");
                        });
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleName")
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_visible");

                    b.HasKey("UserId", "RoleName");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_user_roles_user_id");

                    b.ToTable("user_roles", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_roles_role_name", "role_name IN ('ADOPTER', 'FOSTER', 'TRANSPORTER', 'VETERINARIAN', 'SPONSOR', 'ADMINISTRATOR')");
                        });
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.VerificationDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<string>("DocumentUri")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("document_uri");

                    b.Property<DateTimeOffset>("UploadDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_date");

                    b.Property<long>("VerificationRequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("verification_request_id");

                    b.HasKey("Id");

                    b.HasIndex("VerificationRequestId")
                        .HasDatabaseName("idx_verification_documents_request_id");

                    b.ToTable("verification_documents", (string)null);
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.VerificationRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("RequestedRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("requested_role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RequestedRole", "Status")
                        .HasDatabaseName("idx_verification_requests_user_role_status");

                    b.ToTable("verification_requests", (string)null);
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.VetRequestDetails", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<DateTimeOffset?>("AppointmentDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("appointment_date");

                    b.Property<string>("ClinicName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("clinic_name");

                    b.Property<string>("ReasonForVisit")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason_for_visit");

                    b.Property<bool>("TransportNeeded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("transport_needed");

                    b.HasKey("PostId");

                    b.ToTable("vet_request_details", (string)null);
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.CanMessage", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappyPaws.Domain.Entities.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.ChatParticipant", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.ChatThread", "Thread")
                        .WithMany("Participants")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappyPaws.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.Message", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappyPaws.Domain.Entities.ChatThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.Post", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.RescueApplication", "AssignedApplication")
                        .WithOne()
                        .HasForeignKey("HappyPaws.Domain.Entities.Post", "AssignedApplicationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HappyPaws.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappyPaws.Domain.Entities.Post", "ParentPost")
                        .WithMany("ChildPosts")
                        .HasForeignKey("ParentPostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("HappyPaws.Domain.Entities.LifestyleExpectations", "Expectations", b1 =>
                        {
                            b1.Property<Guid>("PostId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ActivityTempo")
                                .HasColumnType("text")
                                .HasColumnName("expectations_activity_tempo");

                            b1.Property<bool>("GoodWithChildren")
                                .HasColumnType("boolean")
                                .HasColumnName("expectations_good_with_children");

                            b1.PrimitiveCollection<List<string>>("GoodWithPets")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("expectations_good_with_pets");

                            b1.Property<string>("HomeSize")
                                .HasColumnType("text")
                                .HasColumnName("expectations_home_size");

                            b1.Property<bool>("RequiresEnclosedYard")
                                .HasColumnType("boolean")
                                .HasColumnName("expectations_requires_yard");

                            b1.HasKey("PostId");

                            b1.ToTable("posts");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.Navigation("AssignedApplication");

                    b.Navigation("Author");

                    b.Navigation("Expectations");

                    b.Navigation("ParentPost");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.PostLike", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappyPaws.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.PostMedia", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.Post", "Post")
                        .WithMany("Media")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.RescueApplication", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.User", "AdminReviewer")
                        .WithMany()
                        .HasForeignKey("AdminReviewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HappyPaws.Domain.Entities.User", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappyPaws.Domain.Entities.Post", "RescuePost")
                        .WithMany()
                        .HasForeignKey("RescuePostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminReviewer");

                    b.Navigation("Applicant");

                    b.Navigation("RescuePost");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.SponsorshipDetails", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.User", "AdminApprover")
                        .WithMany()
                        .HasForeignKey("AdminApproverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HappyPaws.Domain.Entities.Post", "Post")
                        .WithOne("SponsorshipDetails")
                        .HasForeignKey("HappyPaws.Domain.Entities.SponsorshipDetails", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminApprover");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.SponsorshipProofDocument", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.TransportOffer", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.TransportTask", "Task")
                        .WithMany("Offers")
                        .HasForeignKey("TransportTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappyPaws.Domain.Entities.User", "Transporter")
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.TransportTask", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.Post", "ParentPost")
                        .WithMany()
                        .HasForeignKey("ParentPostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappyPaws.Domain.Entities.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappyPaws.Domain.Entities.Post", "TransportPost")
                        .WithMany()
                        .HasForeignKey("TransportPostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HappyPaws.Domain.Entities.User", "Transporter")
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentPost");

                    b.Navigation("Requester");

                    b.Navigation("TransportPost");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.User", b =>
                {
                    b.OwnsOne("HappyPaws.Domain.Entities.LifestyleProfile", "LifestyleProfile", b1 =>
                        {
                            b1.Property<long>("UserId")
                                .HasColumnType("bigint");

                            b1.Property<string>("ActivityTempo")
                                .HasColumnType("text")
                                .HasColumnName("lifestyle_activity_tempo");

                            b1.PrimitiveCollection<List<string>>("ExistingPets")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("lifestyle_existing_pets");

                            b1.Property<bool>("HasChildren")
                                .HasColumnType("boolean")
                                .HasColumnName("lifestyle_has_children");

                            b1.Property<bool>("HasEnclosedYard")
                                .HasColumnType("boolean")
                                .HasColumnName("lifestyle_has_yard");

                            b1.Property<string>("HomeSize")
                                .HasColumnType("text")
                                .HasColumnName("lifestyle_home_size");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("LifestyleProfile");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.UserBadge", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.User", "User")
                        .WithMany("Badges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.UserDevice", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.User", null)
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.VerificationDocument", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.VerificationRequest", "VerificationRequest")
                        .WithMany("Documents")
                        .HasForeignKey("VerificationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VerificationRequest");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.VerificationRequest", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.VetRequestDetails", b =>
                {
                    b.HasOne("HappyPaws.Domain.Entities.Post", "Post")
                        .WithOne("VetDetails")
                        .HasForeignKey("HappyPaws.Domain.Entities.VetRequestDetails", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.ChatThread", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.Post", b =>
                {
                    b.Navigation("ChildPosts");

                    b.Navigation("Likes");

                    b.Navigation("Media");

                    b.Navigation("SponsorshipDetails");

                    b.Navigation("VetDetails");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.TransportTask", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.User", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("Devices");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("HappyPaws.Domain.Entities.VerificationRequest", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
